### ISSUE TITLE
Build error on Ghost 4.x

### ISSUE THREAD

**Issue by huydhoang** [styxlab/next-cms-ghost#137]
I'm getting this as I upgraded to Ghost v4. Any ideas on where to start looking?

This problem seemingly stems from markdown parsing, so it couldn't build those new routes with `code`, `pre` and `figure` html tags.

```bash
00:33:33.034 | Error occurred prerendering page "/design". Read more: https://nextjs.org/docs/messages/prerender-error
-- | --
00:33:33.035 | TypeError: (0 , hast_util_to_string__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
00:33:33.035 | at /vercel/path0/.next/server/chunks/393.js:232:144
00:33:33.035 | at overload (/vercel/path0/node_modules/unist-util-visit/index.js:27:12)
00:33:33.035 | at node ([33melement<code>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:56:27)
00:33:33.035 | at node ([33melement<pre>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:33.035 | at node ([33melement<figure>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:33.035 | at node ([33mroot[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:33.035 | at visitParents (/vercel/path0/node_modules/unist-util-visit-parents/index.js:29:26)
00:33:33.035 | at visit (/vercel/path0/node_modules/unist-util-visit/index.js:22:3)
00:33:33.036 | at normalizePost (/vercel/path0/.next/server/chunks/393.js:154:25)
00:33:34.204 |  
00:33:34.204 | Error occurred prerendering page "/welcome". Read more: https://nextjs.org/docs/messages/prerender-error
00:33:34.204 | TypeError: (0 , hast_util_to_string__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
00:33:34.204 | at /vercel/path0/.next/server/chunks/393.js:232:144
00:33:34.204 | at overload (/vercel/path0/node_modules/unist-util-visit/index.js:27:12)
00:33:34.204 | at node ([33melement<code>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:56:27)
00:33:34.205 | at node ([33melement<pre>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:34.205 | at node ([33melement<figure>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:34.205 | at node ([33mroot[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:34.205 | at visitParents (/vercel/path0/node_modules/unist-util-visit-parents/index.js:29:26)
00:33:34.205 | at visit (/vercel/path0/node_modules/unist-util-visit/index.js:22:3)
00:33:34.206 | at syntaxHighlightWithPrismJS (/vercel/path0/.next/server/chunks/393.js:221:60)
00:33:34.206 | at normalizePost (/vercel/path0/.next/server/chunks/393.js:154:25)
00:33:34.206 | info - Generating static pages (9/19)
00:33:35.464 |  
00:33:35.465 | Error occurred prerendering page "/write". Read more: https://nextjs.org/docs/messages/prerender-error
00:33:35.465 | TypeError: (0 , hast_util_to_string__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
00:33:35.465 | at /vercel/path0/.next/server/chunks/393.js:232:144
00:33:35.465 | at overload (/vercel/path0/node_modules/unist-util-visit/index.js:27:12)
00:33:35.465 | at node ([33melement<code>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:56:27)
00:33:35.465 | at node ([33melement<pre>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:35.465 | at node ([33melement<figure>[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:35.465 | at node ([33mroot[39m) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
00:33:35.465 | at visitParents (/vercel/path0/node_modules/unist-util-visit-parents/index.js:29:26)
00:33:35.466 | at visit (/vercel/path0/node_modules/unist-util-visit/index.js:22:3)
00:33:35.466 | at syntaxHighlightWithPrismJS (/vercel/path0/.next/server/chunks/393.js:221:60)
00:33:35.466 | at normalizePost (/vercel/path0/.next/server/chunks/393.js:154:25)
00:33:37.685 | info - Generating static pages (14/19)
00:33:39.278 | info - Generating static pages (19/19)
00:33:39.279 |  
00:33:39.280 | > Build error occurred
00:33:39.287 | Error: Export encountered errors on following paths:
00:33:39.288 | /design
00:33:39.288 | /welcome
00:33:39.288 | /write
00:33:39.288 | at /vercel/path0/node_modules/next/dist/export/index.js:493:19
00:33:39.288 | at runMicrotasks (<anonymous>)
00:33:39.289 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
00:33:39.289 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:74:20)
00:33:39.289 | at async /vercel/path0/node_modules/next/dist/build/index.js:956:17
00:33:39.289 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:74:20)
00:33:39.289 | at async /vercel/path0/node_modules/next/dist/build/index.js:830:13
00:33:39.290 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:74:20)
00:33:39.290 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:80:25)
00:33:39.327 | error Command failed with exit code 1.
00:33:39.327 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
00:33:39.345 | Error: Command "yarn run build" exited with 1

```

**Comment by styxlab** [comment]
Can you please publish your content API keys (you can make temporary one that you delete later)? Not sure if this is a Ghost 4.x issue or an issue related to the content in your `/design` page.

**Comment by huydhoang** [comment]
@styxlab Thanks for your response. This is a brand new installation so the content is default by Ghost v4, 
I've created a test content API for you to take a look 
```
https://cms.quantszone.com
7255b7766f9650fc33d089cfa6
```
Running this build locally shows a more detailed error report:

## Server Error
TypeError: (0 , hast_util_to_string__WEBPACK_IMPORTED_MODULE_4__.default) is not a function

`lib\ghost-normalize.ts (137:48) @ eval`
```ts
  135 | try {
  136 |   className = (className || []).concat('language-' + lang)
> 137 |   result = refractor.highlight(nodeToString(node), lang)
      |                                            ^
  138 | } catch (err) {
  139 |   if (prism.ignoreMissing && /Unknown language/.test((err as Error).message)) {
  140 |     return
```

**Comment by styxlab** [comment]
@huydhoang: Thanks for providing the info. I can reproduce with your keys. Will dig into it.

Unrelated to the reported issue, `s3.amazonaws.com` needs to be added to the image domains for image optimizations to work.

**Comment by styxlab** [comment]
@all-contributors please add @huydhoang for issue

**Comment by styxlab** [comment]
@all-contributors please add @huydhoang for bug

**Comment by styxlab** [comment]
Should be fixed. Can you please check?

**Comment by huydhoang** [comment]
Confirmed, worked like a charm. Never had a better experience reporting a bug!
