### ISSUE TITLE
Vercel ISR error

### ISSUE THREAD

**Issue by imtoanle** [styxlab/next-cms-ghost#46]
Hi @styxlab 

My page has 170 posts in homepage
After deployed to Vercel i got below error with JAMIFY_NEXT_ISR enabled.

<img width="1433" alt="Screen Shot 2021-02-14 at 15 40 56" src="https://user-images.githubusercontent.com/4002252/107872219-33bf4b80-6edb-11eb-987f-e9e6bca89fa9.png">

```
[GET] /danh-sach-trang-dia-chi-rut-tien
15:37:24:53
2021-02-14T08:37:28.760Z	a9ca75de-b312-4dc9-88cf-6feb44a734e5	ERROR	Unhandled error during request: Error: Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'
    at getPostBySlug (/var/task/.next/serverless/pages/[...slug].js:9300:134)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getStaticProps (/var/task/.next/serverless/pages/[...slug].js:1549:10)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/[...slug].js:2871:334)
    at async render (/var/task/.next/serverless/pages/[...slug].js:2875:626)
2021-02-14T08:37:28.760Z	a9ca75de-b312-4dc9-88cf-6feb44a734e5	ERROR	Error: Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'
    at getPostBySlug (/var/task/.next/serverless/pages/[...slug].js:9300:134)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getStaticProps (/var/task/.next/serverless/pages/[...slug].js:1549:10)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/[...slug].js:2871:334)
    at async render (/var/task/.next/serverless/pages/[...slug].js:2875:626)
2021-02-14T08:37:28.761Z	a9ca75de-b312-4dc9-88cf-6feb44a734e5	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'","reason":{"errorType":"Error","errorMessage":"Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'","stack":["Error: Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'","    at getPostBySlug (/var/task/.next/serverless/pages/[...slug].js:9300:134)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async getStaticProps (/var/task/.next/serverless/pages/[...slug].js:1549:10)","    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)","    at async renderReqToHTML (/var/task/.next/serverless/pages/[...slug].js:2871:334)","    at async render (/var/task/.next/serverless/pages/[...slug].js:2875:626)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Error: EROFS: read-only file system, open '/var/task/.cache/https%3A%2F%2Fcms.comoex.com%2Fcontent%2Fimages%2F2021%2F02%2Feditor-uploads-2F1549702739553-1549702739552.jpeg.txt'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred
```

I'm not sure why this happened. It would be great if you could take a look.
Thanks

**Comment by styxlab** [comment]
@imtoanle : Welcome to this project. Judging from the error message it looks like an error in the ISR feature. The problem seems to be that whenever a new page is ISR generated with previously unknown images, those images are auto-analyzed and the meta-info is written to the file-system cache. However, the file-system cache can only be written during deploy, after that it is only readable.

Until I have found a fix, you have the following workaround options available, you may want to disable one of the following features in `appConfig.js`.

- disable ISR
- disable image optimization (nextFeatureImages and nextInlineImage)
- disable `fileCache`

The last option is probably best option at hand. Going forward, I probably need to disable the `fileCache` writes on ISR.

**Comment by imtoanle** [comment]
@styxlab It makes sense. Thanks for your explanation
Thank again for your amazing works in this project.

**Comment by styxlab** [comment]
Can you please test ISR with the latest version again? The error should be fixed.

**Comment by imtoanle** [comment]
@styxlab I saw your exception mession in log. But request still returned 502 error.
<img width="852" alt="Screen Shot 2021-02-14 at 21 57 15" src="https://user-images.githubusercontent.com/4002252/107880194-d85b8080-6f0f-11eb-8cd2-1b80af48a9d3.png">
<img width="710" alt="Screen Shot 2021-02-14 at 21 57 27" src="https://user-images.githubusercontent.com/4002252/107880199-e01b2500-6f0f-11eb-87e5-b555d45d8254.png">

This function loaded > 10 seconds so it was killed by Vercel
https://comoex.com/_next/data/mMB3xKBb_vitRw_92p4yU/hop-dong-ky-han-va-hop-dong-tuong-lai-la-gi.json

**Comment by imtoanle** [comment]
@styxlab I found the reason.
When i fast scroll my home page to end. https://comoex.com
Homepage already loaded all 170 posts. So Next loaded 170 jsons and caused overload issue.
Vercel told > 10 seconds for handle request.

<img width="1433" alt="Screen Shot 2021-02-14 at 15 40 56" src="https://user-images.githubusercontent.com/4002252/107880438-59ffde00-6f11-11eb-9390-ca45728e81f9.png">

Do we have feature to limit 10->20 posts in home page / tag page ?

**Comment by imtoanle** [comment]
@styxlab I could limit home page posts by add limit value to ``getAllPosts`` in ``pages/index.tsx``.
I think infinite scroll here is better. Could we implement this ?

**Comment by styxlab** [comment]
Before going into solution mode, I would like to understand your requirements better. How many posts does your site have? Is this a problem after initial deploy, does it occur only on the index page, does it go away after a while or does it persist?

There is also a maxNumberOfPost option available as part of the ISR feature but it does not affect the index page.

**Comment by imtoanle** [comment]
@styxlab My site have total 170 posts. All of them were rendered in home page and tag page.
When i scroll this page. Next js will fetch json data foreach post.

Vercel will be slowed when handle many requests at the same time and they limited 10 seconds for "Serverless Function Execution Timeout (Seconds)". See: https://vercel.com/docs/platform/limits 
So json request got 502 error.

This issue always happen on a site has many posts.
Eg: https://comoex.com/tag/tai-lieu

**Comment by styxlab** [comment]
Thanks for the info, I know these limits but still don't understand why you run into them. Could you please publish 

1. your `appConfig.js` settings (only the ones that deviate from the default settings)
2. publish your Ghost CMS keys, so I can test your site myself (you can create new keys that you can delete afterwards).
3. Does this only happen with ISR? What happens when you disable ISR?

I also don't see any issues when scrolling your site at https://comoex.com/tag/tai-lieu, but maybe some posts are missing there?

**Comment by styxlab** [comment]
@imtoanle: Are you still interested in keeping this thread open or did you find a solution in the meantime?

**Comment by imtoanle** [comment]
@styxlab Sorry. I came back, i got busy few days ago.
The first your fix resolved file cache issue.

Regarding to timed out issue. Please see video https://recordit.co/uGP45cax8M
Version: https://comoex-next-theme-3s9rk1902.vercel.app/tag/tai-lieu
It's working if disable ISR feature

**Comment by styxlab** [comment]
@imtoanle: No problem. Could you publish (temporary) keys, so I can test the site locally? I also notice that you are using a modified version for page navigation.

About the timeouts. Even if you run into them, shouldn't they go away after a while as all sites are regenerated? Still a porblem, I know, but of lesser degree if it's only temporary.

**Comment by imtoanle** [comment]
@styxlab Sure. I tried to add pagination to avoid this issue but it didn't work.
After fast scroll throught 3 pages. ISR called many serverless requests in queue and they're timed out (just my guess).

My key
```
Content API key: b665df815928ee25f9643ca50f
API URL: https://cms.comoex.com
```

**Comment by styxlab** [comment]
I already get timeouts during local building (`yarn build`):

![image](https://user-images.githubusercontent.com/19638263/108212857-ad9b4300-712e-11eb-8fef-61ce618c68b8.png)

You should first look into your Ghost CMS, you may have to lift access limits there.

**Comment by imtoanle** [comment]
@styxlab Thanks! really appreciate your advice.
I 'll have a look and feedback to you soon

**Comment by styxlab** [comment]
@all-contributors please add @imtoanle for bug

**Comment by styxlab** [comment]
Closing as inactive. Can be re-opened anytime.

**Comment by styxlab** [comment]
Closing as inactive. Can be re-opened anytime.
