### ISSUE TITLE
Read-Only File System Error- Vercel

### ISSUE THREAD

**Issue by ramosmikel** [styxlab/next-cms-ghost#55]
Hello,

I have this persistent issue where I keep getting an EROFS when in production on Vercel.

For the following paths: 

'/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'
'./public/rss.xml'

This doesn't happen locally (production) only on Vercel - I haven't tried Netlify yet I will update once I do.

I have two pages which have been added by me:

- 'About' /about
- 'Contact' /contact

UPDATE:

By disabling rssFeed it removed the rss issue.
By disabling fileCache it removed the site-meta issue.

Log:

`[GET] /_next/data/uga8odFSy2oeXWkkOstfj/tag/poems.json
13:01:17:07
 EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at setCache (/var/task/.next/serverless/pages/tag/[...slug].js:7225:25)
    at imageDimensionsFromFile (/var/task/.next/serverless/pages/tag/[...slug].js:7324:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async seoImage (/var/task/.next/serverless/pages/tag/[...slug].js:6344:23)
    at async getStaticProps (/var/task/.next/serverless/pages/tag/[...slug].js:5075:19)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/tag/[...slug].js:1256:334)
    at async render (/var/task/.next/serverless/pages/tag/[...slug].js:1260:626) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'
}
2021-02-26T13:01:20.587Z	209213c8-1b68-4f92-93f4-c01ce62c2bae	ERROR	Error: EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at setCache (/var/task/.next/serverless/pages/tag/[...slug].js:7225:25)
    at imageDimensionsFromFile (/var/task/.next/serverless/pages/tag/[...slug].js:7324:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async seoImage (/var/task/.next/serverless/pages/tag/[...slug].js:6344:23)
    at async getStaticProps (/var/task/.next/serverless/pages/tag/[...slug].js:5075:19)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/tag/[...slug].js:1256:334)
    at async render (/var/task/.next/serverless/pages/tag/[...slug].js:1260:626) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'
}
2021-02-26T13:01:20.589Z	209213c8-1b68-4f92-93f4-c01ce62c2bae	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'","reason":{"errorType":"Error","errorMessage":"EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'","code":"EROFS","errno":-30,"syscall":"open","path":"/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt","stack":["Error: EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'","    at Object.openSync (fs.js:476:3)","    at Object.writeFileSync (fs.js:1467:35)","    at setCache (/var/task/.next/serverless/pages/tag/[...slug].js:7225:25)","    at imageDimensionsFromFile (/var/task/.next/serverless/pages/tag/[...slug].js:7324:3)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async seoImage (/var/task/.next/serverless/pages/tag/[...slug].js:6344:23)","    at async getStaticProps (/var/task/.next/serverless/pages/tag/[...slug].js:5075:19)","    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)","    at async renderReqToHTML (/var/task/.next/serverless/pages/tag/[...slug].js:1256:334)","    at async render (/var/task/.next/serverless/pages/tag/[...slug].js:1260:626)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: EROFS: read-only file system, open '/var/task/.cache/%2Fvar%2Ftask%2Fpublic%2Fsite-meta.png.txt'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred
`

`[GET] /_next/data/uga8odFSy2oeXWkkOstfj/about.json
13:01:17:00
Loaded env from .env.local
2021-02-26T13:01:20.205Z	56c324e7-9d34-4443-a79e-e1ef9a5c5c1a	ERROR	Unhandled error during request: Error: EROFS: read-only file system, open './public/rss.xml'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at getStaticProps (/var/task/.next/serverless/pages/about.js:2730:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/about.js:1256:334)
    at async render (/var/task/.next/serverless/pages/about.js:1260:626) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: './public/rss.xml'
}
2021-02-26T13:01:20.206Z	56c324e7-9d34-4443-a79e-e1ef9a5c5c1a	ERROR	Error: EROFS: read-only file system, open './public/rss.xml'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at getStaticProps (/var/task/.next/serverless/pages/about.js:2730:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)
    at async renderReqToHTML (/var/task/.next/serverless/pages/about.js:1256:334)
    at async render (/var/task/.next/serverless/pages/about.js:1260:626) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: './public/rss.xml'
}
2021-02-26T13:01:20.209Z	56c324e7-9d34-4443-a79e-e1ef9a5c5c1a	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: EROFS: read-only file system, open './public/rss.xml'","reason":{"errorType":"Error","errorMessage":"EROFS: read-only file system, open './public/rss.xml'","code":"EROFS","errno":-30,"syscall":"open","path":"./public/rss.xml","stack":["Error: EROFS: read-only file system, open './public/rss.xml'","    at Object.openSync (fs.js:476:3)","    at Object.writeFileSync (fs.js:1467:35)","    at getStaticProps (/var/task/.next/serverless/pages/about.js:2730:27)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:109)","    at async renderReqToHTML (/var/task/.next/serverless/pages/about.js:1256:334)","    at async render (/var/task/.next/serverless/pages/about.js:1260:626)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: EROFS: read-only file system, open './public/rss.xml'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred`

Please let me know what I can do.

Thank you

**Comment by styxlab** [comment]
@ramosmikel : Welcome to this project! 

1. The first error has been changed to a warning on #47, so it looks like you are running on an older version of this repo. Could you please update to the latest version? It's expected that the file cache can only be written during deploy and not at runtime.

2. I have to dig into the second issue a bit deeper, not sure why feed needs to write to file system.

**Comment by ramosmikel** [comment]
@styxlab My apologies didn't see you replied so fast.

Thanks for all your hard work on this project.
I will merge the fixes on mine.

I disabled rss feed feature since my client doesn't really need it.

Unfortunately, it's for a client so I will be unable to publish or give access.

But if you bare with me I will try get more information. 

From what I remember several pages triggered it, it wasn't just the about.

Thanks for the help.

**Comment by styxlab** [comment]
I localized the `rss.xml` bug, this will be solved in the next release. Please report back, whether or not the latest current release fixes your first error message. Note: While I want to fix these issue, they are uncritical - your site will work regardless.

**Comment by styxlab** [comment]
Just released a new version. These issue should be fixed now. Please report back.

**Comment by styxlab** [comment]
Fixed.
